### ISSUE TITLE
How to Get QQ oauth more Info

### ISSUE THREAD

**Issue by yimiaodaren** [nixzhu/MonkeyKing#10]
In Demo,  scope, get_user_info   But the Block In DIctionary is  	
{"access_token" = XXXX;
    encrytoken = XXXXX;
    "expires_in" = XXXX;
    msg = sucess;
    openid = XXXXX;
    "pay_token" = XXXXXX;
    ret = 0;
    "user_cancelled" = NO;
}
How to get QQ nikename and avatar_url ?

**Comment by Limon-catch** [comment]
Hi, yimiaodaren, you can use the `access_token ` to request the info.

**Comment by yimiaodaren** [comment]
Thank you !!
