### ISSUE TITLE
Rejected by apple review team for reason that have hidden features related to purchase

### ISSUE THREAD

**Issue by ShrinkLynn** [nixzhu/MonkeyKing#101]
Can MonkeyKing set pay related feature as optional？thanks a lot

**Comment by nixzhu** [comment]
I don't think it's a MonkeyKing related issue. Can you paste your reject letter here?

**Comment by ShrinkLynn** [comment]
![image](https://user-images.githubusercontent.com/7589500/30260525-6d6554c2-96fa-11e7-8c9e-f62471a0f775.png)

This is my appeal result.

I though apple may searching related purchase apis in review.

**Comment by ShrinkLynn** [comment]
@nixzhu I appeal again today, and claim that we only use MonkeyKing to share and login... I'm waiting for their reply...

**Comment by xspyhack** [comment]
Shocked! MonkeyKing hasn’t included any payment sdk, just some keywords(**pay**, **alipay**).  💊

**Comment by ShrinkLynn** [comment]
@xspyhack My situation is special, I use AliPay SDK before, and I removed it after rejected and upload a new binary, however, still reject. Then I search my code, only MonkeyKing and few of my undeleted enum type mentioned "AliPay". Another problem may be the Alipay URL Scheme 😂 .

**Comment by ShrinkLynn** [comment]
I appeal and attach the MonkeyKing link to review team and told that we do not use the purchase function, then it success, I'll close the issue, thanks all your help a lot.
