### ISSUE TITLE
你好，微信oAuth  openUrl 之后的 flag 是什么？

### ISSUE THREAD

**Issue by hydyy** [nixzhu/MonkeyKing#109]
我在做的时候 flag 为 true 直接 return 了

![image](https://user-images.githubusercontent.com/1254987/33513370-441830e0-d77c-11e7-93aa-5ce5228e29b7.png)

**Comment by xspyhack** [comment]
It means open url successed

**Comment by hydyy** [comment]
那为什么 return 掉啊，拿不到 完成回调了

**Comment by hydyy** [comment]
okok thx
