### ISSUE TITLE
啥时候支持下 voice，vedio，app 等的分享呢？

### ISSUE THREAD

**Issue by Wangxiaotao** [nixzhu/MonkeyKing#11]

**Comment by nixzhu** [comment]
@Wangxiaotao 版本 0.6 已支持分享 Audio 和 Video 到 WeChat 和 QQ，分享 App 和分享 URL 是一样的。

**Comment by SuperY** [comment]
@nixzhu 分享 支付宝好友 应该也可以做支持吧？

**Comment by nixzhu** [comment]
@SuperY 欢迎 Pull Request

**Comment by cresstoo** [comment]
请问分享App的内容到Wechat之后，是否能像官方SDK那样，点击消息可以直接呼起App里native内容？

**Comment by Wangxiaotao** [comment]
@nixzhu 好的，我尝试下。

**Comment by inatu** [comment]
@Wangxiaotao , 我截取到了支付宝分享过程中的创建的系统剪切板, 但是发现里面的内容是直接 encode 的的它自己的SDK 创建的数据类, 所以应该难度不小. 如果可以通知下我

**Comment by Limon-O-O** [comment]
已支持支付宝分享

**Comment by eilianlove** [comment]
请问微博怎么支持音视频分享呢？ @nixzhu

**Comment by xspyhack** [comment]
@eilianlove 用 URL

**Comment by eilianlove** [comment]
怎么弄呢？我用URL分享到微博，并没有相应的播放按钮，QQ音乐分享到微博就有，是我这边需要配置什么参数，还是说可以在哪儿有参考资料，谢谢 @xspyhack

**Comment by eilianlove** [comment]
然后QQ分享过去，也没有相应的播放按钮，目前就微信正常

**Comment by xspyhack** [comment]
@eilianlove 应该是需要去向微博申请。
