### ISSUE TITLE
twitter

### ISSUE THREAD

**Issue by Heqiao1025** [nixzhu/MonkeyKing#117]
仿照你们twitter的requesttoken获取方案，httpStatusCode是400.请问一下，twitter的hmac-sha1加密方式是常规的么??

**Comment by fyl00** [comment]
这部分我也是参考 [FHSTwitterEngine](https://github.com/natesymer/FHSTwitterEngine) 来的，具体实现看这个 [commit](https://github.com/nixzhu/MonkeyKing/commit/0b8bb24406069da1a47ca8ff8848641ffbbca66d)。

**Comment by Heqiao1025** [comment]
感谢，这个可以，刚试了一下status=200稳稳到手。这周细细品味下。在我翻译过程中我发现oc，swift的charset转义不太一样，oc会忽略不加入%不会自动的转义，而swift会默认将存在%转义？？不知道这里理解的是否有问题？

**Comment by Heqiao1025** [comment]
hook openurl: 有试过么

**Comment by xspyhack** [comment]
Method Swizzling `UIApplication.open(_:options:completionHandler:)` 这个方法不是很简单么

**Comment by Heqiao1025** [comment]
... 是twitter，app跳转如何授权。抓包显示跳转回我们自己app，twittersdk发送了请求
