### ISSUE TITLE
Networking.swift:477:18: error: 'deinitialize()' is deprecated: the default argument to deinitialize(count:) has been removed, please specify the count explicitly     valuePointer.deinitialize()

### ISSUE THREAD

**Issue by jiachenmu** [nixzhu/MonkeyKing#119]
carthage update --platform ios  编译错误

编译环境： Xcode 9.3 ，Swift 4.1

Networking.swift:478:18: error: 'deallocate(capacity:)' is deprecated: Swift currently only supports freeing entire heap blocks, use deallocate() instead
    valuePointer.deallocate(capacity: 1)

MonkeyKing.swift:801:37: error: 'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value
            let statusText = status.flatMap({ $0 }).joined(separator: " ")

**Comment by nixzhu** [comment]
We’ll release a new version to supports Swift 4.1

**Comment by nixzhu** [comment]
@jiachenmu Use the master branch to test please (`github "nixzhu/MonkeyKing" "master"`). Feedback is welcome.

**Comment by jiachenmu** [comment]
可以编译过了，谢谢~
