### ISSUE TITLE
你好，测试Demo，QQ OAuth 获取信息返不了App,  能不能增加微博获取用户信息？

### ISSUE THREAD

**Issue by heronlyj** [nixzhu/MonkeyKing#12]

**Comment by Limon-catch** [comment]
你好，关于“QQ OAuth 获取信息返不了App”的问题，可以提交具体点的信息么，如：QQ版本，或者帮忙Debug下，欢迎 Pull Request。我测试了很多次，无论是点击返回或者登陆完成都会跳转回来。关于微博用户信息，我看这几天有没空加上去。

**Comment by heronlyj** [comment]
QQ版本 v5.9.5.451  iPhone6  iOS9.1
QQ版本 v5.9.1.405  iPhone6  iOS8.1.2

具体情况是这样的： 跳转到QQ授权页面，授权成功，登录，然后就没反应了，多次点击登录，依然没反应。

MockeyKing.swift 的    public class func handleOpenURL(URL: NSURL) -> Bool  没有调用  

微信，微博 授权此方法调用正常

**Comment by Limon-catch** [comment]
如此神奇，我用了iOS9.1，QQ版本也是 v5.9.5.451，iOS8.1，QQ：v5.9.1.451 都是成功的，或者你把Demo上传到gitHub，我看看

**Comment by heronlyj** [comment]
遇到这个问题的原因是 QQ 的OAuth 与 分享分开了，在URL Shemes里需要填入两个 QQXXXXX， tencentXXXXXX。 多谢 Limon-catch ~~~~~~

**Comment by Limon-catch** [comment]
```xml
<dict>
	<key>CFBundleTypeRole</key>
	<string>Editor</string>
	<key>CFBundleURLName</key>
	<string>QQ</string>
	<key>CFBundleURLSchemes</key>
	<array>
		<string>tencent1104881792</string>
		<string>QQ41db2880</string>
	</array>
</dict>

```
