### ISSUE TITLE
MonkeyKing和WeiXinSDK接入到一个工程出现bug

### ISSUE THREAD

**Issue by gongfly678** [nixzhu/MonkeyKing#124]
工程中调用WeiXInSDK的这行代码+(BOOL) registerApp:(NSString *)appi，然后MonkeyKing的分享到微信和朋友圈就会出现bug，MonkeyKing的handleOpenURL中这句UIPasteboard.general.data(forPasteboardType: "content")取出的数据就只有0字节了，pasteboard之前的数据是对的

**Comment by gongfly678** [comment]
@nixzhu 麻烦看一下可以吗

**Comment by nixzhu** [comment]
@gongfly678 你应该更详细地描述你怎么同时使用MonkeyKing和WeiXinSDK的。我猜测是AppDelegate里open url方法里对MonkeyKing的handleOpenURL的调用滞后于WeiXinSDK。再不然，可能WeiXinSDK替换了系统的open url方法，它用完粘贴板就清空数据了。

**Comment by gongfly678** [comment]
微信的openURL方法我给屏蔽掉了，就是微信sdk的这句+(BOOL) registerApp:(NSString *)appi调用了就会有bug，不调用就OK，调用了这个MonkeyKing的handleOpenURL中这句UIPasteboard.general.data (forPasteboardType: "content")取出的数据就只有0字节了。接入微信SDK是当初微信支付用的

**Comment by gongfly678** [comment]
谢谢，好的，我想别的方法处理
