### ISSUE TITLE
可以通过 MonkeyKing 在 iOS 客户端打开微信小程序吗？

### ISSUE THREAD

**Issue by aalenliang** [nixzhu/MonkeyKing#127]
RT

**Comment by CepheusSun** [comment]
我也遇到了同样的问题

**Comment by nixzhu** [comment]
可以，注意miniAppID是gh开头的那个。

**Comment by CepheusSun** [comment]
刚刚在commit列表里面看到了，谢谢

**Comment by aalenliang** [comment]
我只看到分享小程序到微信，怎么打开小程序呢？

**Comment by nixzhu** [comment]
感谢 @aalenliang 贡献代码，从app打开微信小程序 https://github.com/nixzhu/MonkeyKing/pull/128

**Comment by nixzhu** [comment]
@aalenliang 我发现 shared.launchCompletionHandler 没有被调用，它有存在的意义吗？

**Comment by aalenliang** [comment]
@nixzhu 从 App 打开小程序时，小程序可以有返回 App 的能力，打算判断这个情况并且调用 LaunchCompletionHandler，但是我的小程序是有赞的，并没有提供返回 App 的入口，所以我没有测试这个情况。
