### ISSUE TITLE
QQ 分享失败

### ISSUE THREAD

**Issue by iblacksun** [nixzhu/MonkeyKing#13]
我项目中集成了 MonkeyKing 0.6.2，进行 QQ 分享失败。能唤起 QQ，但是 QQ 不能弹出分享界面，也没任何错误提示。

我测试 MonkeyKing 的 Demo 是可以的，而且对比了 Demo 我 我自己项目最后生成的 URL Scheme，没发现异常。

**Comment by nixzhu** [comment]
@iblacksun 最新版本是 0.6。请确保 URL Schemes 已加了 tencent* 和 QQ* 两者（如 Demo），因为分享到QQ个人和空间需要的不一样，也请参考腾讯的文档。

**Comment by iblacksun** [comment]
@nixzhu 多谢，找到原因了。
MonkeyKing line 435 有问题，根据官方文档描述，当 AppID 转成 16 进制不足 8 位时要在前面加 0 补足 8 位。

**Comment by nixzhu** [comment]
@iblacksun 如果可能，请发个 pull request，或者贴出你的改进代码

**Comment by iblacksun** [comment]
@nixzhu 
```
var hexId = String(format: "%02llx", (appID as NSString).longLongValue)
while hexId.characters.count < 8{
    hexId = "0" + hexId
}
let callbackName = "QQ" + hexId
```

**Comment by nixzhu** [comment]
@iblacksun 已放出版本 0.6.5，请测试看看

**Comment by iblacksun** [comment]
@nixzhu 
```
var monkeyking_QQCallbackName: String {
    var callbackName = String(format: "QQ%02llx", (self as NSString).longLongValue)
    while callbackName.characters.count < 0 {
        callbackName = "0" + callbackName
    }
    return callbackName
}
```

这个方法无效。
当 appId 转成十六进制不足 8 位时在```前面用0```补足，如转换后是 6781aea 的话，最后生成的 callbackName 应该是 ```QQ06781aea```

**Comment by nixzhu** [comment]
@iblacksun 感谢反馈，我今早朦胧里还想到这里写错了，可早上准备pod时忘记了

**Comment by nixzhu** [comment]
@iblacksun 再麻烦测试一下版本 0.6.6

**Comment by iblacksun** [comment]
@nixzhu 测试可用了，非常感谢。
