### ISSUE TITLE
分享取消返回结果不对

### ISSUE THREAD

**Issue by MountainHill** [nixzhu/MonkeyKing#132]
微信分享 - 点击关闭 - 返回程序 
期待错误：userCancelled
实际错误：SDKReason unknown

**Comment by nixzhu** [comment]
@MountainHill 你可先试试Master分支，之后可能会发新版

**Comment by nixzhu** [comment]
@MountainHill 看起来你的调查可以发一个PR了，试试吧？

**Comment by MountainHill** [comment]
@nixzhu  真的吗？真的可以吗？那我多调查多测试下，上面那个只是就问题说代码，没有搞懂代码的意思。

**Comment by nixzhu** [comment]
@MountainHill 当然，永远欢迎开发者贡献代码，细心一点就行

**Comment by nixzhu** [comment]
@MountainHill MonkeyKing的错误类型不够完善。需要分析出常见的失败情况，然后定义为更多的enum case，这样使用者更容易判断，而不需要考虑第三方的文档。

至于为何会有“OAuth Failed”相关代码，那是因为handleOpenURL不只是为分享服务，MonkeyKing还有OAuth等功能，一样需要使用handleOpenURL，所以肯定不能去掉相关代码。222行的`deliverCompletionHandler`是你需要关心的，看看能否分析出常见的错误。

用Issue的方式交流就很好，刚好可以有更多思考，也留下文档。

**Comment by nixzhu** [comment]
@MountainHill 目前OAuth Failed里的Error.userCancelled也是最近的一个开发者的PR增加的，你可看看 https://github.com/nixzhu/MonkeyKing/pull/130 ，只是现在看来没有处理分享之类的情况。

**Comment by GTMYang** [comment]
还没解决么？

**Comment by MountainHill** [comment]
> 至于为何会有“OAuth Failed”相关代码，那是因为handleOpenURL不只是为分享服务，MonkeyKing还有OAuth等功能，一样需要使用handleOpenURL，所以肯定不能去掉相关代码。

@nixzhu  OAuth已经在第156行单独处理了，为何还要在Share中再处理一遍呢？

**Comment by nixzhu** [comment]
@MountainHill 一个是OAuth一个是OAuth Failed，处理的内容并不一样。而且要注意`weChatOAuthForCodeCompletionHandler`和`oauthCompletionHandler`，前者更“原始”一点

**Comment by nixzhu** [comment]
@MountainHill 你可通过取消分享，来确定代码执行路径，确保不破坏已有的其它逻辑

**Comment by nixzhu** [comment]
@MountainHill @GTMYang 代码已合并，可从master分支测试。如果可以，请反馈一下使用效果，之后会更新pod版本。

**Comment by nixzhu** [comment]
版本 1.10.0 以放出，请使用并反馈
