### ISSUE TITLE
如果业务需要微信 OAuth 仅返回 code 再通过服务器来请求用户信息

### ISSUE THREAD

**Issue by dismory** [nixzhu/MonkeyKing#14]
目前 MonkeyKing 会直接用 `code` 从本地发起后续请求再进行回调，但我们在 client 不存放 app key，而是选择把 code 交由服务器再进一步获取用户信息。

这实现起来蛮简单，我想提一个 PR，但因为没有 code guideline 不好入手，望 repo 主给一点建议？

**Comment by Limon-catch** [comment]
1. 代码风格可以参考这个[swift-style-guide](https://github.com/raywenderlich/swift-style-guide)，Spacing改为4。
2. 我还没想到优雅地方法实现这个需求，目前想到的有两个方法：

	一种是修改Account：
	```swift
	public enum Account: Hashable {

        case WeChat(appID: String, appKey: String?)

    }

	```

	另外一种是拦截AppDelegate的方法：



	```swift
	func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {

		guard !URL.scheme.hasPrefix("wx") else {
					
			// DO Something

			return
		}

        if MonkeyKing.handleOpenURL(url) {
            return true
        }

        return false
    }

	```

如果你有更优雅的方法就更好了！
谢谢反馈！

**Comment by Limon-catch** [comment]
我简单写了下，你可以Clone下来看看。应该是可以针对这种需求了。

**Comment by dismory** [comment]
赞效率👍
方案一（目前的方案）比我想到的方案优雅😂

另有一个设计上的疑问，既然几乎总会在 app 入口调用 registerAccont，能否在后续调用 oauth 时仅传入 Account 类型而不再需要构造一个 Account，就像分享 message 一样，这里有什么别的考量么？

**Comment by Limon-catch** [comment]
因为OAuth是后来加入的，一开始没考虑到。我晚上看看。

**Comment by dismory** [comment]
同样面对这个问题的还有判断某个 App 是否安装的方法也是在 enum 上实现的

**Comment by Limon-catch** [comment]
想起来了，OAuth是不需要再构建Account的，因为一般都可以直接传入AppKey，不需要自己用code。所有在Demo中，是优先考虑有appKey的Account，现在Demo中是有两个Acount的。

**Comment by Limon-catch** [comment]
然后是'判断某个 App 是否安装的方法'，直接可以这样'account.isAppInstalled'，在微博的Demo中`-viewDidAppear`有用了下。

**Comment by dismory** [comment]
在我们的项目里只有 app target 里的 AppDelegate 知道如何 construct 这些 account，其它模块只关心调用即可，我自己目前的方式是写了一个叫 MonkeyKingBar 的 helper 类来集中管理和访问…

**Comment by dismory** [comment]
> 想起来了，OAuth是不需要再构建Account的，因为一般都可以直接传入AppKey，不需要自己用code。所有在Demo中，是优先考虑有appKey的Account，现在微信的Demo中是有两个Acount的。

这个不太明白，我的疑惑是，具体发起 OAuth 的模块为何一定要自己 constrct account，而不能隐式依赖在 app launch 时候配置好的？

**Comment by Limon-catch** [comment]
你的意思说，OAuth的时候不传入account？

**Comment by dismory** [comment]
是的，判断客户端是否安装时同理

**Comment by dismory** [comment]
这是我在 MonkeyKingBar 的实现，一来集中维护 WeChat account，二来为了能在 Objective-C 写的 AppDelegate 里调用 MonkeyKing 的注册方法（Objective-C 不支持 Swift 的 enum）

```swift
import Foundation
import MonkeyKing

@objc public class MonkeyKingBar: NSObject {
    
    public private(set) static var wechat: MonkeyKing.Account? = nil

    public static func registerWeChat(WithAppID appID: String) {
        wechat = .WeChat(appID: appID, appKey: nil)
        MonkeyKing.registerAccount(wechat!)
    }

}
```

**Comment by Limon-catch** [comment]
后来加入OAuth的时候，没梳理好，传入Acount是为了判断需要OAuth的类型，目前还没想出什么好方法替代，就算不传入acount，也得传入一个enum做判断吧。如果你想到什么好方法，欢迎PR。
