### ISSUE TITLE
有支付宝登录的例子吗？

### ISSUE THREAD

**Issue by OctMon** [nixzhu/MonkeyKing#146]
业务需要支持支付宝登录，已经用了MonkeyKing非常省事，不想再把支付宝SDK加到项目里来
https://docs.open.alipay.com/218/105326/

**Comment by nixzhu** [comment]
目前没有Alipay的OAuth支持，欢迎PR

**Comment by Limon-O-O** [comment]
已支持 `支付宝App` 授权，网页暂不支持
