### ISSUE TITLE
QQ 网页授权

### ISSUE THREAD

**Issue by inatu** [nixzhu/MonkeyKing#16]
如果没有安装 QQ, 无法打开网页授权页面

```
2015-11-19 14:53:39.589 China[1989:80597] -canOpenURL: failed for URL: "mqqapi://" - error: "(null)"
```

**Comment by Limon-catch** [comment]
MonkeyKing暂时不支持QQ的网页授权，我智商不足，还没能看得懂QQ的文档，上次研究了2个小时都没弄好，果断放弃。

**Comment by inatu** [comment]
Hi, 截取了一个 QQ 请求授权的 URL以及返回, 不知道能不能提供些思路
http://xui.ptlogin2.qq.com/cgi-bin/xlogin?appid=716027609&pt_3rd_aid=209656&style=35&s_url=http%3A%2F%2Fconnect.qq.com&refer_cgi=m_authorize&client_id=209656&redirect_uri=auth%3A%2F%2Fwww.qq.com&response_type=token

#access_token=3E7B066CB53C8E4DFC43E2AC2042FEC5&expires_in=7776000&openid=540E0FA57FCADB6544154333FB5CB305&pay_token=12BBD8ABF23C67256F14A23A2B13493F&state=test&ret=0&pf=openmobile_ios&pfkey=7b88519439d7274fd13a62934a090852&auth_time=1447923804460&page_type=1.

**Comment by Limon-catch** [comment]
赞，我缺的就是`redirect_uri`，我看QQ文档的时候就是绕进了这个`redirect_ui`。你是用QQ SDK上截取的？

**Comment by inatu** [comment]
OK, 做好后跟我说一下, 对, 我用 QQ 的 SDK截取的, 如果可以做到麻烦通知我一下.

**Comment by Limon-catch** [comment]
OK

**Comment by Limon-catch** [comment]
已泪奔.....现在成功获取了token，但......居然说`msg = "app has no privilege to use this api";
    ret = 100031;`我也是醉了，难道QQ是不能同时支持网页和App授权的？

**Comment by inatu** [comment]
应该不是吧, ShareSDK 是支持网页和 App 授权的, 你应该是没有申请权限吧, 搜索你的错误代码.

http://wiki.open.qq.com/wiki/【QQ登录】公共返回码说明

**Comment by Limon-catch** [comment]
后来发现是API的原因，现在可以App和Web授权。你试试

**Comment by inatu** [comment]
好的， 提个小建议，感觉你如果用swift的异常处理机制可以将api设计的更好，包括微博分享视频等各种异常的fatal error，本来想自己完善下的，不过因为最近开发任务比较重，在设计我们4.0版本的重写，所以没有时间。

总之感觉这个框架想法不错。

**Comment by Limon-catch** [comment]
本来也想用，最近任务也比较重，我在重新开发3.0，过段时间有空再改 :)
