### ISSUE TITLE
Wechat SDK1.8.6.1 是否有逻辑变更

### ISSUE THREAD

**Issue by SuperY** [nixzhu/MonkeyKing#161]
https://mp.weixin.qq.com/s/1ItLDQrQidgbMkAY2DZAmA

**Comment by Limon-O-O** [comment]
暂时未知，我看了微信的文档，说得不清不楚，没弄懂为什么要开发者注册 `Universal Link`。
难道微信要用网页来跳转回第三方应用？还是 Apple 要求微信在跳转回第三方应用时，先通过 `Universal Link` 校验第三方应用是否安全？

为了不出幺蛾子，可按微信的文档配置 `Universal Link`，目前应该还不会影响 `MonkeyKing` 的使用。

原因：

1. `MonkeyKing` 只在 `application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] =
        [:]) -> Bool` 处理其它应用跳到本应用时带过来的 `urlScheme`

2. 通过 `Universal Link` 跳转到本应用时，触发接受参数的方法是：
    a. `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool ` 内的 `launchOptions` 的 `NSUserActivity`
可以处理 `Universal Link` 跳转回来自己应用
    b. `func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool`

3. 目前我个人觉得微信不太可能废弃 `UIApplication.shared.open(url)` 的方式来跳转，而是通过 `Universal Link` 来跳转

**Comment by dorentus** [comment]
但是使用了新版微信 SDK 之后，新版微信的确是用 Universal Link 实现应用<->微信的跳转的 🤔 

比如从 app 到微信，调用 `-[UIApplication openURL:options:completionHandler:]`，传递了这样一个 URL: `https://help.wechat.com/app/【redacted  weixin_app_id】/sendreq/?wechat_auth_context_id=【redacted hex string】&wechat_app_bundleId=【redacted bundle id】`通过 Universal Link 打开了微信。

微信还强制开发者需要到微信后台去绑定 app bundle id 和 universal link URL，从而在应用跳转到微信时做校验，并且使用应用的这个 universal link URL 传参数跳回应用。应用需要在 `-application: continueUserActivity: restorationHandler:` 里面去调用 `+[WXApi handleOpenUniversalLink:delegate:]`，旧的 `-application:openURL:sourceApplication:annotation:` 里面调用 `+[WXApi handleOpenURL:delegate:]` 仅为兼容旧版微信之用。

当然，现阶段新版微信还是可以兼容使用旧版 SDK 协议的 app 的，但是几乎可以预见他们会有在将来某个时候废弃旧协议的计划。

**Comment by SuperY** [comment]
@Limon-O-O 新版系统下，Universal Link 跳转App是不会感受到打开网页这一步，Apple可能做过优化和预判？
所以替换是必然，不过考虑在老系统上的体验，废弃open(url) 可能需要较长时间。

**Comment by iblacksun** [comment]
微信将在 2020 年 3 月开始禁止使用老 SDK 调用微信，强制使用 Universal Link
https://developers.weixin.qq.com/community/develop/doc/00062412e00e4878f8290f35457801

**Comment by SuperY** [comment]
[微信开放平台移动应用 SDK 更新提醒](https://mp.weixin.qq.com/s/R5lUNDDbghGfnwBir8srJw)
平台将于近期开始逐步对iOS 旧版本 SDK（版本号低于1.8.6.1）的能力进行阶梯式调整，具体计划如下：
1. 2020年3月20日起对旧版本 SDK 发起的分享增加“未验证应用”安全提示
2. 2020年6月1日起限制旧版本 SDK 使用微信分享、微信登录、打开小程序、一次性订阅消息等能力

**Comment by xspyhack** [comment]
按照我的理解，是不是支持了 Universal Links 后，其实不再需要配置 URL scheme 和 Queries Schemes？但文档里还是要这两个是作为备选/过渡方案么？

**Comment by nuomi1** [comment]
wechat_auth_token 和 wechat_auth_context_id 没啥头绪，为了安全还是切换回官方 SDK 吧。

（这 SDK API 设计得可真，一肚子气……

**Comment by lexrus** [comment]
我加上了 Universal Link 支持，麻烦各位 review 一下：
https://github.com/nixzhu/MonkeyKing/pull/171
