### ISSUE TITLE
分享到微信后，显示 “未验证应用”，可以解决吗？

### ISSUE THREAD

**Issue by LeoAiolia** [nixzhu/MonkeyKing#173]
![图片](https://user-images.githubusercontent.com/16910025/86989056-2ebf4e80-c1cc-11ea-8daa-f1b15e549968.png)

**Comment by Limon-O-O** [comment]
这是在微信开方平台上的账号还没验证吧

**Comment by LeoAiolia** [comment]
> 这是在微信开方平台上的账号还没验证吧

不是，网上查，好像是通用链接没配，要换微信分享的SDK了。

**Comment by nixzhu** [comment]
可看看这个PR，支持微信Universal Link
https://github.com/nixzhu/MonkeyKing/pull/171
