### ISSUE TITLE
MonkeyKing (1.16.0)还不支持微信universalLink，什么时候将universalLink发上去啊？

### ISSUE THREAD

**Issue by kennenfromchina** [nixzhu/MonkeyKing#175]

**Comment by nixzhu** [comment]
请先使用master分支参与测试

**Comment by wdlgame** [comment]
@nixzhu @lexrus  hi, master 最新分支无 MonkeyKing+QQUniversalLink.swift  文件，看最新的PR 地址是 MonkeyKing/MonkeyKing+QQUniversalLink.swift， 文件存放位置应该是错误了，所以pod下来是没有该文件的.

**Comment by lexrus** [comment]
@wdlgame 确实，我修一下。

**Comment by nixzhu** [comment]
@wdlgame @lexrus 我刚修了，请再试一遍
