### ISSUE TITLE
请问支持微信universalLink的版本什么时候上。master的代码可以用么

### ISSUE THREAD

**Issue by PaulWyw** [nixzhu/MonkeyKing#177]

**Comment by nixzhu** [comment]
请先使用master分支测试

**Comment by PaulWyw** [comment]
maste代码r试过了，加上universalLink以后，分享功能就不可用了

**Comment by lexrus** [comment]
@PaulWyw 请确认一下 Universal Link 是否配置正确，包括服务端的 apple-app-site-association 是否正确。
我们的 App 用 master 分支实测已经可以正常使用 Universal Link 分享。
