### ISSUE TITLE
生成 MonkeyKing.xcframework 后无法使用

### ISSUE THREAD

**Issue by lexrus** [nixzhu/MonkeyKing#178]
我用如下脚本生成新的 xcframework：
``` bash
xcodebuild archive -project "China.xcodeproj" \
	-scheme "MonkeyKing" -configuration Release \
	-sdk iphonesimulator \
	-archivePath "Build/MonkeyKing/Simulator" \
	SKIP_INSTALL=NO \
	BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild archive -project "China.xcodeproj" \
	-scheme "MonkeyKing" -configuration Release \
	-sdk iphoneos \
	-archivePath "Build/MonkeyKing/iOS" \
	SKIP_INSTALL=NO \
	BUILD_LIBRARY_FOR_DISTRIBUTION=YES
xcodebuild -create-xcframework \
	-framework Build/MonkeyKing/Simulator.xcarchive/Products/Library/Frameworks/MonkeyKing.framework \
	-framework Build/MonkeyKing/iOS.xcarchive/Products/Library/Frameworks/MonkeyKing.framework \
	-output xcframeworks/MonkeyKing.xcframework
```

使用时会出现这些问题：
<img width="450" alt="Screen Shot 2020-09-17 at 8 46 39 PM" src="https://user-images.githubusercontent.com/219689/93472969-fd7ba100-f927-11ea-97d6-80db1e19ecb8.png">

<img width="1368" alt="Screen Shot 2020-09-17 at 8 46 58 PM" src="https://user-images.githubusercontent.com/219689/93472999-07050900-f928-11ea-98eb-0207c7ca6f2b.png">

搜索了一下可能是因为这个 bug：
https://forums.swift.org/t/frameworkname-is-not-a-member-type-of-frameworkname-errors-inside-swiftinterface/28962

**Comment by lexrus** [comment]
我改了项目生成的 framework 的 target 的名字之后才可以正常编译使用...

<img width="312" alt="Screen Shot 2020-09-17 at 9 09 23 PM" src="https://user-images.githubusercontent.com/219689/93474551-12593400-f92a-11ea-9e52-d9c047e4f27a.png">
<img width="407" alt="Screen Shot 2020-09-17 at 9 10 24 PM" src="https://user-images.githubusercontent.com/219689/93474643-3583e380-f92a-11ea-991f-7b17eb99a70e.png">

**Comment by nixzhu** [comment]
还没研究过 XCFramework，有可能直接从 Package.swift 生成吗？😄

**Comment by lexrus** [comment]
fixed in https://github.com/nixzhu/MonkeyKing/releases/tag/pre-1.17.0
@nixzhu
