### ISSUE TITLE
Extensions里面有一个UIImage的压缩算法，存在死循环概率

### ISSUE THREAD

**Issue by zhusongyu** [nixzhu/MonkeyKing#179]
![Snip20200923_2](https://user-images.githubusercontent.com/33612211/93976244-49f13180-fdab-11ea-91ff-cdcbd9c649ae.png)

proportion有可能为1，当为1的时候，会导致死循环。比如maxSize为200 * 1024，当binaryCompression压到300k或者200多k左右为极限的时候，返回到这里proportion一直为1，newSize不变，就会导致死循环了。
我加了一个判断，虽然粗暴，但不会死循环了。
 var proportion = CGFloat(currentMiniIamgeDataSize / maxSize)
 proportion = proportion == 1 ? 2 : proportion

**Comment by nixzhu** [comment]
方便发个PR来修复吗？

**Comment by zhusongyu** [comment]
#180 

嗯，已提。

**Comment by nixzhu** [comment]
已合并
