### ISSUE TITLE
微信分享跳转微信出现正在连接之后直接返回app，有遇到过的朋友吗？

### ISSUE THREAD

**Issue by sjxt** [nixzhu/MonkeyKing#192]
universalLink 用的是mob直接生成的一个，我在微信那边说是最新的sdk的问题，但是我也没有导入SDK呀

**Comment by nuomi1** [comment]
`handleOpenUserActivity` 调用了吗？

**Comment by sjxt** [comment]
> `handleOpenUserActivity` 调用了吗？

调用了的

**Comment by nuomi1** [comment]
> > `handleOpenUserActivity` 调用了吗？
> 
> 调用了的

能提供一下微信校验时跳回 App 的 `NSUserActivity.webpageURL` 和剪切板的信息吗？

**Comment by sjxt** [comment]
> > > `handleOpenUserActivity` 调用了吗？
> > 
> > 
> > 调用了的
> 
> 能提供一下微信校验时跳回 App 的 `NSUserActivity.webpageURL` 和剪切板 `UIPasteboard.general.items` 的信息吗？

昨天我更新了MonkeyKing  刚才试了一下已可以分享了

**Comment by nuomi1** [comment]
已解决。
