### ISSUE TITLE
Binary target zip file naming problem

### ISSUE THREAD

**Issue by CodeEagle** [nixzhu/MonkeyKing#200]
As latest PR mentioned, the zip file also named 'MonkeyKingBinary.framework.zip'

**Comment by CodeEagle** [comment]
Unzip name not right

Need sticking to the target name ' MonkeyKingBinary'


![image](https://user-images.githubusercontent.com/2311352/121806773-d1593a80-cc83-11eb-93ef-d5133a902e64.jpeg)

**Comment by nixzhu** [comment]
@CodeEagle Give v2.2.1 a try.
