### ISSUE TITLE
weChatOAuthForCode 确认弹窗

### ISSUE THREAD

**Issue by huangboju** [nixzhu/MonkeyKing#201]
![image](https://user-images.githubusercontent.com/14818224/131642272-c49264b5-c073-4d1d-9666-825b0d840464.png)

用这个接口，跳转微信会有确认弹窗

![image](https://user-images.githubusercontent.com/14818224/131642363-20570181-483a-4bb0-8e9e-c32e095a53f0.png)

微信自带的接口不会有弹窗

**Comment by huangboju** [comment]
研究了下，初步估计是微信新的链接变了
新：
`https://help.wechat.com/app/appid/auth/?scope=snsapi_userinfo&state=state&wechat_auth_context_id=wechat_auth_context_id&wechat_app_bundleId=wechat_app_bundleId`
旧：
`weixin://app/appid/auth/?scope=snsapi_userinfo&state=Weixinauth`

**Comment by nixzhu** [comment]
@huangboju 继续研究下去，然后贡献代码吧

**Comment by huangboju** [comment]
> @huangboju 继续研究下去，然后贡献代码吧

[PR](https://github.com/nixzhu/MonkeyKing/pull/204/files)已提交，期待早日合入

**Comment by nixzhu** [comment]
PR 已合并，请先使用 master 分支测试，一段时间后会考虑打新的 Tag
