### ISSUE TITLE
微信 6.3.9 已不再支持指定 imageUrl 来分享图片

### ISSUE THREAD

**Issue by dismory** [nixzhu/MonkeyKing#22]
和微信团队的人确认这点，微信会向 app 返回 `Unsupport` 错误。

在这备忘一下，要将之前 `ImageURL` 类型的分享移除掉。

**Comment by dismory** [comment]
或者降级成 webpage 的分享

**Comment by Limon-O-O** [comment]
会不会和 `URL` 雷同了？

**Comment by dismory** [comment]
确实，本质是一样的
