### ISSUE TITLE
QQ App Name 错误

### ISSUE THREAD

**Issue by iblacksun** [nixzhu/MonkeyKing#25]
当手机上已安装 QQ 进行第三方授权时，跳转到 QQ 的登录界面，显示的 app 名称是 「nixApp」，经检查是 MonkeyKing line 1137 有问题，```localizedInfoDictionary``` 是一个 empty dictionary，而不是  nil.

**Comment by Limon-O-O** [comment]
已改，请测试 :)

**Comment by iblacksun** [comment]
@Limon-O-O 多谢，新代码我这测试通过，CocoaPods 能否更新个版本，我看之前微信收藏功能也还没发布。

**Comment by Limon-O-O** [comment]
好滴，晚上发个。
