### ISSUE TITLE
QQ Web OAuth 失败

### ISSUE THREAD

**Issue by iblacksun** [nixzhu/MonkeyKing#27]
当设备上没安装 QQ 时进行 OAuth 授权会弹出 WKWebView，输入密码之后点击授权出现空白页面且回调没有被调用，经检查是 MonkeyKing.swift line 894 造成，注释掉之后正确跳转到 line 903， 能正确得到 access_token 且关闭 WKWebView，不知道基于什么考虑要加上 line 894？

**Comment by Limon-O-O** [comment]
是 QQ 网页授权的回调地址的原因，Sorry，之前没测试完全。
