### ISSUE TITLE
A free logo for MonkeyKing ^__^

### ISSUE THREAD

**Issue by lexrus** [nixzhu/MonkeyKing#3]
![monkeykinglogo 3x](https://cloud.githubusercontent.com/assets/219689/10532531/e390c632-73f1-11e5-87c2-661f3adecb2a.png)

**Comment by RayPS** [comment]
The best of 2015

**Comment by RayPS** [comment]
![artboard](https://cloud.githubusercontent.com/assets/1941540/10534190/4a90a766-7407-11e5-9d02-8bb26153bf33.png)

How about the Nyan Monkey

**Comment by lexrus** [comment]
@RayPS 🤓👍🏾

**Comment by RayPS** [comment]
![](https://media.giphy.com/media/bE5qi2tiSfdZu/giphy.gif)

**Comment by nixzhu** [comment]
感谢两位分别设计的Logo，实在难以选择，就让它们永远待在这里吧！

**Comment by Limon-catch** [comment]
哈哈
