### ISSUE TITLE
isAppInstalled should be class function which takes parameter as app type (qq,wechat...)

### ISSUE THREAD

**Issue by peiweichen** [nixzhu/MonkeyKing#31]
isAppInstalled should be class function which takes parameter as app type (qq,wechat...)
现在 isAppInstalled 是 Account对象的变量 ， 我觉得这种使用方法比较合理 -> `MokeyKing. isAppInstalled(.QQ)`

**Comment by nixzhu** [comment]
见仁见智

**Comment by xspyhack** [comment]
MonkeyKing提供的主要功能是分享到各社交平台/移动支付，使用者只需要按使用文档，调用相应的接口即可，是否安装相应的App由内部来判断，使用者并不需要关心这个问题。所以它没有必要暴露出来。

**Comment by Jinxiansen** [comment]
@xspyhack  但是有时候需要判断是否安装了摸个app，若没有安装则需要隐藏分享/登录按钮的。

**Comment by nixzhu** [comment]
好吧，刚添加了`MonkeyKing.isAppInstalled(app:)`
测试用
``` ruby
pod 'MonkeyKing', :git => 'https://github.com/nixzhu/MonkeyKing.git'
```
