### ISSUE TITLE
QQ 国际版 / 日本版支持

### ISSUE THREAD

**Issue by HarukaMa** [nixzhu/MonkeyKing#33]
今天在尝试使用的时候发现 QQ 分享的 Activity 一直不出现，然后发现是 `canOpenURL` 失败了。于是下载了一个日本版的 QQ（帐号正好在日区），打开 Info.plist 发现 URL Scheme 都是 `mqqi*` 或者 `QQi*`，估计国际版的也一样。

我正在尝试自己用暴力的方式魔改（加一个 `QQi` 的类型），但是感觉这方式很……不优雅。

请问是否有考虑支持国际版的 QQ 分享？

**Comment by HarukaMa** [comment]
魔改似乎很成功，但还是感觉强行加一个新类型的方式不是很好，所以就不 PR 了……

**Comment by Limon-O-O** [comment]
👍

**Comment by HarukaMa** [comment]
Anyway, this is the bad approach:

https://github.com/HarukaMa/MonkeyKing/commit/3ccf7e12436847ef242dce29807841aa192c5b8f

**Comment by HarukaMa** [comment]
嗯测试发现剪贴板 type 还是 `com.tencent.mqq.api.apiLargeData`……我魔改过度了（并且当时没测试

**Comment by HarukaMa** [comment]
WontFix?

iPhone$B$+$iAw?.(B

H28/05/05 2:53$B!"(BLimon <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by HarukaMa** [comment]
So why would you close an issue without fixing it, and yet give no explanation of closing?

**Comment by xspyhack** [comment]
We haven't plan to support International QQ yet.

I'd highly recommended you checkout the differences between QQ and International QQ and then update your code.

 https://github.com/HarukaMa/MonkeyKing/commit/3ccf7e12436847ef242dce29807841aa192c5b8f seems 👍 for the first glance.

```swift
public enum Account: Hashable {

        case WeChat(appID: String, appKey: String)
        case QQ(appID: String, isInternational: Bool)
```
`let scheme = isInternational ? "mqqiapi" : "mqqapi://"`

**Comment by HarukaMa** [comment]
Will try to make it cleaner and more generic...

2016-06-17 16:32 GMT+09:00 xspyhack <notifications@github.com>:
