### ISSUE TITLE
通过Pod进来后，Networking这个类还不能引用

### ISSUE THREAD

**Issue by arden** [nixzhu/MonkeyKing#35]
为啥通过Pod进来后，Networking这个类还不能引用？这样Oauth的时候获取不了第三方用户的用户基本信息，昵称、头像等。

**Comment by Limon-O-O** [comment]
Networking 不提供外部使用，建议使用 [Alamofire](https://github.com/Alamofire/Alamofire)，另外请仔细看 Examples，里面都有具体的案例，谢谢！
