### ISSUE TITLE
你好，请问QQ的OAuth中如何填写scope

### ISSUE THREAD

**Issue by wsof401** [nixzhu/MonkeyKing#36]
官方SDK中使用的是一个数组。MonkeyKing中使用的是字符串。

**Comment by xspyhack** [comment]
使用逗号分隔。
如 `scope=get_user_info,list_album,upload_pic,do_like`

**Comment by wsof401** [comment]
@xspyhack 如果想获取QQ的用户信息呢

**Comment by xspyhack** [comment]
@wsof401 请看官方文档[使用Authorization_Code获取Access_Token](http://wiki.connect.qq.com/使用authorization_code获取access_token)。
> 请求用户授权时向用户显示的可进行授权的列表。 
可填写的值是API文档中列出的接口，以及一些动作型的授权（目前仅有：do_like），如果要填写多个接口名称，请用逗号隔开。
例如：scope=get_user_info,list_album,upload_pic,do_like
不传则默认请求对接口get_user_info进行授权。
建议控制授权项的数量，只传入必要的接口名称，因为授权项越多，用户越可能拒绝进行任何授权。
