### ISSUE TITLE
To Add : wechat web Oauth support?

### ISSUE THREAD

**Issue by peiweichen** [nixzhu/MonkeyKing#38]
Dear,
Plan To Add : wechat web Oauth support?

**Comment by xspyhack** [comment]
Hi,
WeChat can OAuth only App. 

> 1、目前移动应用上微信登录只提供原生的登录方式，需要用户安装微信客户端才能配合使用。
2、对于Android应用，建议总是显示微信登录按钮，当用户手机没有安装微信客户端时，请引导用户下载安装微信客户端。
3、对于iOS应用，考虑到iOS应用商店审核指南中的相关规定，建议开发者接入微信登录时，先检测用户手机是否已安装微信客户端（使用sdk中isWXAppInstalled函数 ），对未安装的用户隐藏微信登录按钮，只提供其他登录方式（比如手机号注册登录、游客登录等）。

[移动应用微信登录开发指南](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317851&token=&lang=zh_CN)

**Comment by peiweichen** [comment]
Thanks bro@xspyhack
