### ISSUE TITLE
构建一个微信 order 时候 `signType=SHA1` 参数疑问

### ISSUE THREAD

**Issue by alfredcc** [nixzhu/MonkeyKing#40]
我在集成问下微信支付的时候遇到的一点问题，希望得到帮助。
因为项目中并没有用到pay.php中的配置，所已我在客户端自己通过服务端返回的参数够建了一个 `MonkeyKing.Order` 下面是一些示例代码
```swift
// 构建一个 MonkeyKing.Order `signType` 为 `MD5`
let orderString = "weixin://app/\(appID)/pay/?nonceStr=\(nonceStr)&package=Sign=WXPay&partnerId=\(partnerId)&prepayId=\(prepayId)&timeStamp=\(timestamp)&sign=\(sign)&signType=MD5"

let order = MonkeyKing.Order.WeChat(URLString: orderString)

MonkeyKing.payOrder(order) { result in
    print("result: \(result)")
}
```
然而这段代码 Don't Works

然后我查看 pay.php 的源码，发现在签名时候用的是 MD5 的加密方式 ` $sign=strtoupper(md5($sign));`
但是在返回给客户端的是`$iOSLink=sprintf("weixin://app/%s/pay/?nonceStr=%s&package=Sign%%3DWXPay&partnerId=%s&prepayId=%s&timeStamp=%s&sign=%s&signType=SHA1",$APP_ID,$input["noncestr"],$MCH_ID,$input["prepayid"],$input["timestamp"],$sign);`
这里最后一个参数却是 `Type=SHA1` 
让我感到很困惑

**Comment by alfredcc** [comment]
另外相同的参数`appid` `noncestr` `nonce_str` `prepaid` `package`  `partnered` `timestamp` 使用微信SDK 可以成功调用

**Comment by xspyhack** [comment]
@alfredcc 

1，微信的 API 里面的确没有 `signType` 的参数，但是 SDK 内部却增加了这一参数。原因估计可以从 [接口规则](https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=4_1) 这里得到一些信息。
对于官方 Sample 进行 hook，得到如下信息：
```
weixin://app/wxb4ba3c02aa476ea1/pay/?nonceStr=4824052cd5d6189de7a2f670c30e3e9c&package=Sign%3DWXPay&partnerId=1305176001&prepayId=wx20160524150013f128d40b0f0686216392&timeStamp=1464073213&sign=C3A2513AF01E39726DD031888A423893&signType=SHA1
```

2, 请确认你的 `sign` 和其他参数是正确的，`package=Sign=WXPay`，这里应该把 `Sign=WXPay` 中的 `=` 进行进行 URL encode。

如果还有其他问题，再一起讨论。 :D

**Comment by alfredcc** [comment]
Yep， 进行一次 URL encode 就好了👍
感谢及时回复  :D
