### ISSUE TITLE
分享之后留有 ShareSDK 的小角标。麻烦问一下怎么显示成自己App的名称

### ISSUE THREAD

**Issue by dowhilenet** [nixzhu/MonkeyKing#41]
你好。MonkeyKing很好用的，遇到了如题的问题。想请问一下怎么去解决。

谢谢！

**Comment by xspyhack** [comment]
I'm so sorry for I can't catch your problem.

Can you show me a screenshot for your detail issues?

You should't use **ShareSDK's OAuth key/secretKey** in your project, if not, for example when you share media to WeChat, you will see "share from ShareSDK".

**Comment by dowhilenet** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/10379476/16796049/21b1c0c8-4913-11e6-92bd-f8b5cd7c495a.jpg)

**Comment by xspyhack** [comment]
I guess you had use ShareSDK's OAuth key in your project!
Just replace it with yours. It can register your app in [open.weixin.qq.com](https://open.weixin.qq.com/cgi-bin/frame?t=home/app_tmpl)

**Comment by dowhilenet** [comment]
Thanks,I try it.
