### ISSUE TITLE
Can I share News with image，title and abstract？

### ISSUE THREAD

**Issue by jasonji84** [nixzhu/MonkeyKing#42]
MonkeyKing is good to use. I'd like to use the kit to replace damn ShareSDK. I have a question. How can I share one news with image at left, and title with abstract at right? 

Thank you very much

**Comment by LanfordCai** [comment]
MonkeyKing can help you share image with title and description, but the layout of them are determined by the platform you share to. For instance, the share card of QQ and old version WeChat put the image at left, title and abstract at right, however, latest Wechat put the image to right.

Hope it helps :)
