### ISSUE TITLE
MonkeyKing not callback

### ISSUE THREAD

**Issue by jasonji84** [nixzhu/MonkeyKing#43]
My app can share data to other platforms successfully. However, when coming back to my app, MonkeyKing has performed the programs below. 

MonkeyKing.shareMessage(message) { result in
    print("result: (result)")
}

The demo hasn't such problems and shareSDK is also O.K. Any idea about this?

**Comment by Limon-O-O** [comment]
Do you implement this function correctly?

```swift
func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {

        if MonkeyKing.handleOpenURL(url) {
            return true
        }

        return false
    }
```

**Comment by jasonji84** [comment]
I have not missed these codes in application function.

**Comment by xspyhack** [comment]
Hi @jasonji84 ,

Do you mean `MonkeyKing.shareMessage(_:)` won't callback when shared and came back to your app?

Please confirm it can come back to your app and called `func application(_:openURL:sourceApplication:annotation:) -> Bool`.

And then you can make a breakpoint in the method `MonkeyKing.handleOpenURL(_:)`(line[136] of `MonkeyKing.swift`), and step by step debugging to see what happen.

By the way, if you are using MonkeyKing to share something to QQ, you need to set `URL Scheme` correctly. It looks like `QQxxxxxxxx`(QQ number with hex encoded), and the demo incorrectly.

Hope helps!

**Comment by zzyspace** [comment]
Hi @xspyhack ,

How to get QQxxxxxxx ? When using QQ SDK to share, I never have this problem

**Comment by zzyspace** [comment]
thx!
