### ISSUE TITLE
What time support swift3.0?

### ISSUE THREAD

**Issue by Mosaics** [nixzhu/MonkeyKing#49]

**Comment by xspyhack** [comment]
Swift 3.0 version is coming soon.

There is a pr (#48) for Swift 3.0 and we are reviewing these code.

**Comment by Mosaics** [comment]
@xspyhack  what time?

**Comment by xspyhack** [comment]
@Mosaics We push the Swift 3.0 version code a day ago, and it will be released soon.

**Comment by amoyio** [comment]
Yooooo~
