### ISSUE TITLE
没有对支付宝"scene"这个字段做处理

### ISSUE THREAD

**Issue by JinghuangLiu** [nixzhu/MonkeyKing#53]
支付宝已经支持分享到会话和生活圈，没有对支付宝"scene"这个字段做处理，代码中是这一行："scene": [keyUID: 12]

**Comment by LanfordCai** [comment]
这几天比较忙，周末看看哈，如果愿意的话，可以发个 PR~

**Comment by LanfordCai** [comment]
@JinghuangLiu 已经添加了分享图片和链接到生活圈的功能，不过目前支付宝[不支持分享纯文本](https://doc.open.alipay.com/docs/doc.htm?treeId=193&articleId=105276&docType=1)。

**Comment by JinghuangLiu** [comment]
好的 感谢

发自我的 iPhone
