### ISSUE TITLE
组装message的时候 用UIImage(data: Data()) 这样的方式加载图片URL, 分享失败

### ISSUE THREAD

**Issue by cedared** [nixzhu/MonkeyKing#55]
组装message的时候 thumbnail用UIImage(data: Data()) 这样的方式加载图片URL, 分享失败, 没有任何提示,直接跳到微博APP之后就直接跳回来了, 把thumbnail设为nil 或者UIImage(named: String()) 就可以正常分享. 问题可能出在哪里呢? 是图片过大还是什么?

**Comment by cedared** [comment]
好吧 果然是太大了.......加了参数 切一下图片就好了.....

**Comment by Limon-O-O** [comment]
@cedared ，你测试到微博的图片最大限制是多少么？MonkeyKing 没对微博的图片大小进行限制，只对微信图片限制了

**Comment by cedared** [comment]
不好意思 并没有测到上限 因为thumbnail只会在发布分享消息的时候显示在微博上, 发布完成之后在timeline上实际是不显示的, 建议直接处理成长边300以内 就足够用了

**Comment by cedared** [comment]
@Limon-O-O

**Comment by Limon-O-O** [comment]
get
