### ISSUE TITLE
分享到qq  无法回调

### ISSUE THREAD

**Issue by fq050766** [nixzhu/MonkeyKing#57]
跳回来的url:  tencent(*appid*)://response_from_qq?source=qq&source_scheme=mqqapi&error=0&version=1

在handleOpenURL(:_)   的 UIPasteboard.general.data(forPasteboardType: "com.tencent.tencent\(account.appID)")这里  ，执行的结果是nil

**Comment by Limon-O-O** [comment]
appID 之类的是否配置正确？
详细再对一遍？或者把你的 AppID 和 AppKey 替换到 MonkeyKing 内的 Demo，试试是否有此问题

**Comment by fq050766** [comment]
@Limon-O-O 试了下，还真是appid的问题，用我的AppID，分享之后的跳回来的url前缀是"tencent"，用demo里面appid分享之后回调url是"QQ"开头的。在`handleOpenURL(_:)`里面把"tencent"开头的前缀全部当做OAuth授权来处理了。

**Comment by fq050766** [comment]
发现问题了，因为我没有配置QQ开头的URL  Schemes
