### ISSUE TITLE
各个平台的是否可以以插件方式加载

### ISSUE THREAD

**Issue by aelam** [nixzhu/MonkeyKing#59]
现在所有平台的支持都写在一个文件, 如果有10个分享那就会非常庞大

能否每个平台一个类, 类似`UIActivity` 让MoneyKing自动加载
这样在扩展的时候MoneyKing不需要动

**Comment by nixzhu** [comment]
简洁的 API 更重要，用 enum 对于开发也很安全（不易遗漏）。
你可看看之前一个被拒绝的 PR https://github.com/nixzhu/MonkeyKing/pull/19

**Comment by aelam** [comment]
虽然这很enum 可是一点都不面向协议 面向协议才是关键

发自我的 iPhone

**Comment by nixzhu** [comment]
好的 PR 是增加功能，或改进已有功能（维护）。而换一种方法实现只不过是一种个人练习罢了。再说了，协议真就那么好？

**Comment by aelam** [comment]
在4,5的时候看不出优势, 但是如果是10个的话没增加一个MonkeyKing本身就要做大规模的改动. 最理想的情况是在别人提交PR的时候只需要提交一个扩展类

只是建议 
当然你的项目你做主. 
这两个链接可以看看 
http://www.jianshu.com/p/cfc4859ebd6e
http://www.jessesquires.com/enums-as-configs/

**Comment by xspyhack** [comment]
Hi @aelam 

在思考设计模式的时候，不能脱离真实的场景。
对于 `POP` 的优劣网上有太多讨论，Swift 2 之后的 `POP` 的优势在于可以提供默认实现。

但在 MonkeyKing 里面，各个平台的实现几乎没有什么共同的地方可以抽离出来，不同的平台除了大流程上相同，在具体的实现上都是完全不同的。

如果没有了共同的部分，没有了默认实现，那么对比 枚举 和 协议 这两种不同的实现方式，协议就没有任何的优势。

对于扩展性，枚举的确不如协议，但是这是一个取舍的过程，如果考虑上 MonkeyKing 的初衷，就能明白为什么会使用枚举了。
