### ISSUE TITLE
你好，我遇到了一个问题想和你请教一下

### ISSUE THREAD

**Issue by ShaoShuaiiOS** [nixzhu/MonkeyKing#60]
就是我的项目现在遇到了一点小问题，查了很多不知道怎么解决，正好我的项目也用到了MonkeyKing，就想可不可以问问你。

**Comment by nixzhu** [comment]
如果不是和 MonkeyKing 有关的问题，原则上不该出现在这里。
如果你使用 iMessage，请留下你的 Apple ID 看看有没有可能帮到你。

**Comment by ShaoShuaiiOS** [comment]
谢谢，19940813a@163.com

**Comment by ShaoShuaiiOS** [comment]
我已经解决了，谢谢你。
