### ISSUE TITLE
新浪微博网页授权能提供SDK那个网页授权页面么

### ISSUE THREAD

**Issue by JinghuangLiu** [nixzhu/MonkeyKing#62]
现在你们是用开放平台API接口做的，需要新浪微博SDK提供的那个网页授权页面。

**Comment by Limon-O-O** [comment]
不知道你指哪个网页界面？发个截图看看？

**Comment by JinghuangLiu** [comment]
![62be33feb785c75218bbbc2f66087faf](https://cloud.githubusercontent.com/assets/6930613/21215001/4d50a56a-c2d9-11e6-996f-0d74a97bca47.png)

使用微信SDK授权接口授权，没有安装客户端或者没有配置LSApplicationQueriesSchemes都会出现

**Comment by Limon-O-O** [comment]
你确定这个是网页？而不是官方 SDK 自己写的 View？我感觉不像。
还有一点是，如果连微博都没安装的，登录这个界面样式其实是没什么所谓了

**Comment by JinghuangLiu** [comment]
确定网页。

**Comment by JinghuangLiu** [comment]
技术是无所谓，然而产品有所为。

**Comment by Limon-O-O** [comment]
因为官方 SDK 没开源，也不知道它走的是哪一个流程。
第一步还是需要逆向官方 SDK，拿到这个网页的网址，然后还要分析它走的流程，比如是登录之后回调的网址等等。
我们目前还未打算走官方 SDK 的流程，毕竟网页授权的流程是有文档的。

> 或者和你家产品说，目前实现不了，如果换成官方 SDK，App 体积会大几兆 🤓

**Comment by JinghuangLiu** [comment]
我hook了下。地址是这个：
https://open.weibo.cn/oauth2/authorize?packagename=com.sina.weibo.SNWeiboSDKDemo&response_type=code&scope=all&aid=01AssrtiqApLg-FKq9GYVtZ3Z95-_zqpOpTvLzUcRcdTxtE0Y.&key_hash=22191242ac93f71da72492a63395bf40&redirect_uri=http%3A%2F%2Fwww.sina.com&version=003143000&client_id=2045436852

问题是：aid和key_hash对应的值不知道怎么生成的。
