### ISSUE TITLE
DeliverCompletionHandler 仅仅只有一个 Bool 参数可能不太足够

### ISSUE THREAD

**Issue by zzyspace** [nixzhu/MonkeyKing#66]
因为这个操作的回调应该要有三种可能性, 操作成功 \ 操作失败 \ 取消操作. 而目前少了 `取消操作` 这个情况的处理.

**Comment by Limon-O-O** [comment]
不是少了 `取消操作`，而是少了 `失败操作`。
主要是`失败操作` 太难触发了，不知从何入手，所以 `MonkeyKing` 暂时还不会添加此功能。
