### ISSUE TITLE
微信登录 短信授权 点击“确认登录”没有回调事件

### ISSUE THREAD

**Issue by Zhugy** [nixzhu/MonkeyKing#67]
在收到微信登录 发送的手机短信时，点击链接可以回跳到 app，但是在“确认登录”时却没有点击事件，无法获取微信返回的信息，这个问题好像最近才有的

**Comment by Limon-O-O** [comment]
亲测，可用。你测试的时候，请注意 [oauthCompletionHandler](https://github.com/nixzhu/MonkeyKing/blob/master/Sources/MonkeyKing.swift#L1487-24) 是否不为 `nil`
