### ISSUE TITLE
Alipay 的回调 判定

### ISSUE THREAD

**Issue by CodeEagle** [nixzhu/MonkeyKing#68]
代码中写死了要有 prefix `ap`，这个优点不合理，阿里那边也是开放了这个回调头的，所以这边应该要处理下

**Comment by xspyhack** [comment]
确实有缺陷，支付宝并没有要求回调的 URL Scheme 必须以 **ap** 开头，这个是开发的时候习惯性（如微信规定 wx + xxxx，微博是 wb + xxxx）造成的。

官方的例子是判断 **host** 是不是 **safepay**，这个好像也没有规定只有支付宝能够使用，无法保证。
但按照目前已知的，按照官方例子的做法会比现在的方法好一点。

如果你有时间和兴趣贡献，可以提个 PR。

XD
