### ISSUE TITLE
发现QQ分享，不管是好友还是QQ空间，deliver并没执行回调！微信无此问题，请问是什么原因？

### ISSUE THREAD

**Issue by Mosaics** [nixzhu/MonkeyKing#71]
<img width="581" alt="121" src="https://cloud.githubusercontent.com/assets/13238978/22181305/dac69ec8-e0c4-11e6-9379-46154ab9b0f8.png">
用法如图

**Comment by Mosaics** [comment]
@nixzhu

**Comment by nixzhu** [comment]
@Mosaics 刚才测试了一下 Demo China，QQ 分享确实不会回调。AppDelegate 里也没有收到 open url，估计是新版 QQ 没有主动返回，待进一步观察。

**Comment by Mosaics** [comment]
@nixzhu 好的，感谢，新年快乐

**Comment by Limon-O-O** [comment]
@Mosaics ，现在还会有这种情况么？我没测出来。。。。

**Comment by mqch295** [comment]
遇到同样问题，，QQ没进入回调。。。
