### ISSUE TITLE
Bug: OAuth for WeChat and cancel in WeChat lead to "WeChat Share" logic instead of "OAuth Failed"

### ISSUE THREAD

**Issue by puttin** [nixzhu/MonkeyKing#74]
dict:
![image](https://cloud.githubusercontent.com/assets/1543629/22232265/5af7978c-e223-11e6-8662-ab73c8e908be.png)

then wrong completionHandler is called

![image](https://cloud.githubusercontent.com/assets/1543629/22232278/7b120f66-e223-11e6-904e-519b1b80cab3.png)

**Comment by puttin** [comment]
This is screenshot from Demo App (China).
Production Environment also have this problem.

**Comment by Limon-O-O** [comment]
Yes, MonkeyKing does not handle `cancel`.
Only true or false.

**Comment by puttin** [comment]
Although MonkeyKing (version at issue created time) does not handle `cancel`, the logic inside MonkeyKing still lead to the problem.

And I just test on version 1.3.0

The China Demo App still has the problem.

More detail to reproduce:

1. Tap WeChat
2. Tap OAuth
3. Tap Cancel
4. In MonkeyKing `handleOpenURL` it go to `sharedMonkeyKing.deliverCompletionHandler?(.failure…`
