### ISSUE TITLE
share text to qzone 报错

### ISSUE THREAD

**Issue by OnePieceLv** [nixzhu/MonkeyKing#75]
分享 text 到 qzone 时报系统繁忙的错误，如果 share info 带上 media 类型的数据就没有问题了，比如 image。demo 也有同样的问题。

**Comment by nixzhu** [comment]
稍微观察了一下，暂时不清楚原因，也许和新版QQ有关，可能需要重新分析QQ的分享SDK。

**Comment by morpheus1984** [comment]
@nixzhu 请问如何分析qq分享以及类似第三方的sdk？有什么工具或者思路呢？

**Comment by nixzhu** [comment]
简单来说，目前的第三方分享都是构造一些数据放在系统粘贴板中（突破沙盒限制传递数据），然后通过openURL唤醒对应的App，目标App再去粘贴板中取得数据（一些数据也可以编码在openURL的URL中）。各家App不同，数据格式及URL就不同。最后目标App同样再通过openURL唤醒“源”App以返回，源App处理这个openURL的信息，就能知道是否分享成功了。

可参考 @LanfordCai 写的[无 SDK 实现支付宝分享](http://lanfordcai.github.io/2016/01/27/%E6%97%A0-SDK-%E5%AE%9E%E7%8E%B0%E6%94%AF%E4%BB%98%E5%AE%9D%E5%88%86%E4%BA%AB/)

**Comment by morpheus1984** [comment]
@nixzhu 了解了，谢谢啦。有空试试

**Comment by Limon-O-O** [comment]
@OnePieceLv ，会不会是分享太频繁？ Text 带上 `UUID().uuidString`，试试？
Demo 也会有此问题，请问是怎么处罚？
