### ISSUE TITLE
请教作者一个问题

### ISSUE THREAD

**Issue by Mosaics** [nixzhu/MonkeyKing#79]
微信分享、支付回调的过程中为什么会先闪过启动页然后才显示调用，这个是什么原因？ 发现其他APP有些是有的，有些没有。

**Comment by Limon-O-O** [comment]
这个没留意过，可能是需要对相应的分享作出处理，比如你分享东西到微信，微信调整样式方便你分享。
跳转到微信的时候有`月亮`的启动界面，可能此启动界面就是为了不让你看到下面的样式调整

**Comment by Mosaics** [comment]
@Limon-O-O  非常感谢
