### ISSUE TITLE
可以支持到Swift4吗？

### ISSUE THREAD

**Issue by IanHsia** [nixzhu/MonkeyKing#89]

**Comment by nixzhu** [comment]
现在Swift 4的特性还不够稳定，可能要过一段时间才会考虑转换。

**Comment by nixzhu** [comment]
Now we have a Swift 4 branch https://github.com/nixzhu/MonkeyKing/tree/swift-4
You can try with `pod 'MonkeyKing', :git => 'https://github.com/nixzhu/MonkeyKing.git', :branch => 'swift-4'`
