### ISSUE TITLE
OAuth callback 调用两次

### ISSUE THREAD

**Issue by iblacksun** [nixzhu/MonkeyKing#9]
未安装新浪微博时采用网页进行认证，OAuth callback 会调用两次，第一次调用 error 不为空，包含 redirect url 信息，第二次 callback dictionary 中包含了有效的 uid 和 accessToken.

**Comment by Limon-catch** [comment]
谢谢反馈，已修复 :)

**Comment by iblacksun** [comment]
测试通过，多谢。
