### ISSUE TITLE
MonkeyKing.SupportedPlatform.weibo.isAppInstalled is not update with Cocoapods

### ISSUE THREAD

**Issue by yeziahehe** [nixzhu/MonkeyKing#92]
`MonkeyKing.SupportedPlatform.weibo.isAppInstalled` in demo is ok, but not work in cocopods.

I find source code, in demo SupportedPlatform has isAppInstalled, but not in cocoapods.

Is cocoapods not update?

**Comment by yeziahehe** [comment]
@Limon-O-O

**Comment by Limon-O-O** [comment]
`1.3.0` has released !!!
Try again !

**Comment by yeziahehe** [comment]
Thanks, solved too quickly.

I have another question, I find Pocket has be added, but it don't have func like `MonkeyKing.Message.pocket`, pocket can also open app

**Comment by Limon-O-O** [comment]
After Pocket`s OAuth, you can add items to Pocket with accessToken directly.

[More Pocket API](https://getpocket.com/developer/docs/v3/add)

**Comment by yeziahehe** [comment]
Yes, I know this way. But this should OAuth web first.

I just see it can open pocket to OAuth first then return, and then click share button again, it will add item directly.

![731502116374_ pic](https://user-images.githubusercontent.com/8090437/29031313-664373ae-7bc0-11e7-854c-d958a9d8961d.jpg)

**Comment by Limon-O-O** [comment]
MonkeyKing also can open pocket to OAuth and return automatically.

![img_2688](https://user-images.githubusercontent.com/11239742/29032164-0b8192fe-7bc3-11e7-8ba5-a00581e00b89.png)

**Comment by yeziahehe** [comment]
sorry, I test MonkeyKing but I did not install Pocket.

Thank you for open source, Thank you for contrubiting MonkeyKing for developers!

And i want to know, do you have plan to add Evernote & youdao?

**Comment by Limon-O-O** [comment]
Not plane to add youdao.
Two years ago, Evernote only supports SDK. [#118](https://github.com/evernote/evernote-cloud-sdk-ios/issues/118)

**Comment by yeziahehe** [comment]
Thanksl.

I find v1.3.0 has changer result from bool to DeliverResult, how can I differentiate success and failure?
