### ISSUE TITLE
swift4:Value of type 'Substring' has no member 'addingPercentEncoding'

### ISSUE THREAD

**Issue by bulolo** [nixzhu/MonkeyKing#93]
![image](https://user-images.githubusercontent.com/10026498/29056723-8a68f0f2-7c37-11e7-8a8d-76552d61d710.png)

**Comment by nixzhu** [comment]
Make sure you change your project's **Swift Language Version** to Swift 4.0 (in Build Settings).

**Comment by bulolo** [comment]
@nixzhu  yes ,i am sure
![image](https://user-images.githubusercontent.com/10026498/29057963-5ceea06e-7c40-11e7-9024-15ee5c8e22c0.png)
![image](https://user-images.githubusercontent.com/10026498/29057968-666648e0-7c40-11e7-9952-25c40e072a14.png)

**Comment by nixzhu** [comment]
How about in `PROJECT`?

**Comment by bulolo** [comment]
@nixzhu 
![image](https://user-images.githubusercontent.com/10026498/29058267-f4df9602-7c41-11e7-8f4e-7ded00646daa.png)

**Comment by nixzhu** [comment]
Did you use the latest Xcode 9 beta 5?

**Comment by bulolo** [comment]
不是版本问题。
我把```  let substring = string[startIndex..<endIndex]```
改成：``` let substring = String(string[startIndex..<endIndex])```
就编译通过了

![image](https://user-images.githubusercontent.com/10026498/29058284-126b6b92-7c42-11e7-8449-c443b4e4f144.png)

**Comment by bulolo** [comment]
Xcode 9 beta 4

**Comment by nixzhu** [comment]
You need to use the latest beta to test. Swift 4 is not in stable, API may changed in new beta.

**Comment by bulolo** [comment]
thanks,trying Xcode 9 beta 5 now.
