### ISSUE TITLE
现在还支持国外的那些比如推特,非死不可这些吗

### ISSUE THREAD

**Issue by ghost320** [nixzhu/MonkeyKing#94]
好像自动提示里面没有这些...是不支持了吗

**Comment by nixzhu** [comment]
代码里有Twitter支持，文档里没有。没有Facebook支持。

**Comment by ghost320** [comment]
![image](https://user-images.githubusercontent.com/11917824/29261986-02ec53ee-8105-11e7-8d85-674a54622e4e.png)
我下载的工程里看到是有推特,不过自己的没有自动提示~

**Comment by nixzhu** [comment]
最新版本是1.3.0，你是否更新了？

**Comment by ghost320** [comment]
额,好吧,看来我版本太旧了,我就今天CocoaPods安装的,居然是1.2.3版本...

**Comment by ghost320** [comment]
我CocoaPods只能装1.2.3的...
