### ISSUE TITLE
可以分享图片链接吗？

### ISSUE THREAD

**Issue by mqch295** [nixzhu/MonkeyKing#95]
现有需求是需要分享一篇文章，文章是以H5页面方式加载，但是分享需要时需要将文章的首图作为thumbnail。大概看了一下源码，thumbnail为UIImage?,求教如何处理！

**Comment by nixzhu** [comment]
How about download it first?

**Comment by mqch295** [comment]
目前唯一的办法，只能用隐藏的uiimageview先下载，然后读取传递了。

**Comment by nixzhu** [comment]
I think the first image in your article is represented by a URL. You can download it as Data, and create a UIImage with the data. No need a hidden UIImageView.

**Comment by mqch295** [comment]
嗯嗯，对哦，，sorry,,目前只有这样了，，谢谢！
