### ISSUE TITLE
问下签名方式问题

### ISSUE THREAD

**Issue by flymzero** [nixzhu/MonkeyKing#97]
看你的php端是用md5加密的， 那如果用HMAC-SHA256签名，那 signType填什么

**Comment by xspyhack** [comment]
WeChat or Alipay?

WeChat:
Following the doc https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_1, sign_type should be `HMAC-SHA256` if you are using `HMAC-SHA256`.


Alipay:
Following the doc https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7386797.0.0.wg80Bv&source=search&treeId=291&articleId=106115&docType=1 and https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.rWhhQ5&treeId=193&articleId=105465&docType=1, Alipay only supports RSA(SHA1WithRSA) and RSA2(SHA256WithRSA).

**Comment by flymzero** [comment]
thanks very much
