### ISSUE TITLE
Demo 真机报错  dyld: Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by aloveric** [nixzhu/MonkeyKing#98]
`dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /var/containers/Bundle/Application/466FE1F5-60AF-4FE3-95B8-FF543F2C37B6/China.app/China
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/466FE1F5-60AF-4FE3-95B8-FF543F2C37B6/China.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/containers/Bundle/Application/466FE1F5-60AF-4FE3-95B8-FF543F2C37B6/China.app/Frameworks/libswiftCore.dylib'`

<img width="1278" alt="screen shot 2017-08-19 at 12 46 00 am" src="https://user-images.githubusercontent.com/8198881/29468698-ec66b0b2-8477-11e7-8229-acc728c127a4.png">

**Comment by nixzhu** [comment]
You may need to clean your project or clean Xcode/DerivedData.
It's not a MonkeyKing related issue, I'll close it.

**Comment by aloveric** [comment]
Thanks
